### ISSUE TITLE
TypeError: Argument passed to EntityDiscovery must be an instance of PathValidator

### ISSUE THREAD

**Issue by martin-klima** [jakubhnilicka/adminic_tools#3]
The website encountered an unexpected error just after install via UI. 

It is multilanguage site with admin_toolbar version: 8.x-1.19 installed.

`TypeError: Argument 2 passed to Drupal\adminic_tools\EntityDiscovery::__construct() must be an instance of Drupal\Core\Path\PathValidator, none given, called in /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 268 in Drupal\adminic_tools\EntityDiscovery->__construct() (line 33 of /var/www/vhosts/marbeton.dev/web/modules/custom/adminic_tools/src/EntityDiscovery.php) #0 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Component/DependencyInjection/Container.php(268): Drupal\adminic_tools\EntityDiscovery->__construct(Object(Drupal\Core\Entity\EntityTypeManager)) #1 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService(Array, 'adminic_tools.e...') #2 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal.php(158): Drupal\Component\DependencyInjection\Container->get('adminic_tools.e...') #3 /var/www/vhosts/marbeton.dev/web/modules/custom/adminic_tools/adminic_tools.module(17): Drupal::service('adminic_tools.e...') #4 [internal function]: adminic_tools_toolbar() #5 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('adminic_tools_t...', Array) #6 /var/www/vhosts/marbeton.dev/web/core/modules/toolbar/src/Element/Toolbar.php(81): Drupal\Core\Extension\ModuleHandler->invokeAll('toolbar') #7 [internal function]: Drupal\toolbar\Element\Toolbar::preRenderToolbar(Array) #8 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(376): call_user_func(Array, Array) #9 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(448): Drupal\Core\Render\Renderer->doRender(Array) #10 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #11 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array) #12 /var/www/vhosts/marbeton.dev/web/sites/default/files/php/twig/594c02ebc9f75_html.html.twig_wBkxgpJYqh60vIPunjAKuvySB/Kw_PaCWY3UndaDv_DnTMG3sDPGkLnbu0YD_UYYQrXj0.php(80): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #13 /var/www/vhosts/marbeton.dev/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_4a0387b265d067bab2d2de06a8ead777749d03cb5cf7ba23df40bc8d00a80437->doDisplay(Array, Array) #14 /var/www/vhosts/marbeton.dev/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array) #15 /var/www/vhosts/marbeton.dev/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array) #16 /var/www/vhosts/marbeton.dev/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array) #17 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/modules/sy...', Array) #18 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(435): Drupal\Core\Theme\ThemeManager->render('html', Array) #19 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #20 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array) #21 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/Renderer.php(574): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #22 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #23 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #24 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #25 /var/www/vhosts/marbeton.dev/vendor/symfony/http-kernel/HttpKernel.php(149): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #26 /var/www/vhosts/marbeton.dev/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #27 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /var/www/vhosts/marbeton.dev/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /var/www/vhosts/marbeton.dev/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #31 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #32 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /var/www/vhosts/marbeton.dev/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /var/www/vhosts/marbeton.dev/web/core/lib/Drupal/Core/DrupalKernel.php(656): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /var/www/vhosts/marbeton.dev/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #36 {main}.`

**Comment by martin-klima** [comment]
Install via drush ended with another error:
`Error: Call to undefined function Drupal\adminic_tools\_adminic_tools_entity_discovery() in
Drupal\adminic_tools\Permissions->getPermissions() (line 24 of
/var/www/vhosts/marbeton.dev/web/modules/custom/adminic_tools/src/Permissions.php) #0 [internal function]:
Drupal\adminic_tools\Permissions->getPermissions()
#1 /var/www/vhosts/marbeton.dev/web/core/modules/user/src/PermissionHandler.php(149): call_user_func(Array)
#2 /var/www/vhosts/marbeton.dev/web/core/modules/user/src/PermissionHandler.php(108):
Drupal\user\PermissionHandler->buildPermissionsYaml()
#3 /var/www/vhosts/marbeton.dev/vendor/drush/drush/lib/Drush/Role/Role8.php(41):
Drupal\user\PermissionHandler->getPermissions()
#4 /var/www/vhosts/marbeton.dev/vendor/drush/drush/commands/pm/pm.drush.inc(1177):
Drush\Role\Role8->getModulePerms('adminic_tools')
#5 /var/www/vhosts/marbeton.dev/vendor/drush/drush/includes/command.inc(422): drush_pm_enable('adminic_tools')...`
